/**
 * Angular Runtime X-Ray - Main Export
 * Auto-generated by Angular Runtime X-Ray Extension
 */

export { Performance, TrackChangeDetection, XRayClient } from './probe-decorator';

// Re-export types
export type { PerformanceData, WebSocketClient } from './probe-decorator';
